---
html_document:
  theme: journal
  toc: yes
  toc_float: yes
  number_sections: yes
  code_folding: show
  
title: "Proyecto estadística"
author: "Paula Uzcategui | Sebastian Pedraza | Alexander Martinez"
output:
  html_document:
    df_print: paged
lang: "es-ES"
date: "2023 Dic 06"
---

# Análisis de sensibilidad del precio de productos de la canasta familiar a factores externos

## Introducción

### La problemática

En Colombia la producción agricola se enfrenta a retos complejos como el cambio climático, la interrupción de suministros y la competencia externa. Factores como la inflación, el aumento de precios de insumos, transporte, almacenamiento, fenómenos climáticos y malos negocios con intermediarios terminan afectando al productor [2] (Portafolio). Por ejemplo, el diario Portafolio reporta que hace 18 meses producir una hectárea de papa costaba alrededor de \$22 millones y los valores de hoy están cercanos a los \$40 millones por hectárea. Además de esto los pequeños y medianos productores tienen que competir con importaciones de paises tecnificados donde la producción es mas económica y eficiente. La papa es un caso importante, es un producto esencial para muchos hogares y hoy existe un exceso de oferta en comparación con la demanda[1] (Razon publica).

Desde esta problemática consideramos que es fundamental conocer las tendencias del mercado y los factores que afectan a los cultivos. En el siguiente proyecto realizamos algunos análisis para ayudar a los productores a tomar desiciones informadas y que estas les permitan ser competitivos en el mercado. 

### ¿Cómo abordaremos el problema?

Utilizaremos datos históricos de los precios de diferentes productos agricolas en diferentes centros mayoristas del pais, nos centramos en los datos producidos por el departamento nacional de estadística, DANE. Elegimos la **región andina** de Colombia para acotar el problema, y también nos enfocamos en  los productos cosechados en esta región. Analizaremos la variabilidad del precio a lo largo del tiempo con el objetivo de identificar los productos más estables, buscando identificar los productos que podrían tener una rentabilidad más segura. Usaremos datos de algunos factores relacionado en la cadena de producción o suministro, como la inflación, los precios de diferentes insumos y los patrones de precios que siguen estos productos anualmente.

### Técnica 

Para analizar los datos utilizaremos principalmente las medidas de tendencia central estadística como la media y la desviación estándar. Con estas identificaremos la variabilidad de los productos a lo largo del tiempo. A su vez usaremos la correlación para buscar posibles relaciones entre insumos y productos.

### Ayudar a los productores 

El objetivo de nuestro proyecto es generar herramientas e información para apoyar la toma de desiciones en la actividades de producción agricola, con un enfoque en la producción de pequeña o mediana escala. 


## Los datos usados

En nuestros análisis utilizamos 2 conjuntos de datos principalmente.

1. DANE (2023) Sistema de Información de Precios y Abastecimiento del Sector Agropecuario (SIPSA). Gobierno de Colombia. Recuperado el 15 de Noviembre de 2023 de: https://www.dane.gov.co/index.php/estadisticas-por-tema/agropecuario/sistema-de-informacion-de-precios-sipsa#precios-mayoristas. 
2. Datset Inflación total y meta, recuperado del portal del Banco de la República. Recuperado el 15 Nov de 2023 de: https://www.banrep.gov.co/es/estadisticas/inflacion-total-y-meta


Datos recolectados por el DANE como parte de la operación SIPSA (Sistema de información de Precios y Abastecimiento) desde el 2012 hasta la fecha. Los conjuntos de datos disponbles son: Precios Mayoristas, Abastecimientos de Alimentos e Insumos y Factores Asociados a la Producción Agropecuaria.

### Datos productos, precios mayoristas

Las series históricas de precios mayoristas tienen 5 variables, la fecha en la cual se tomó la medición del precio del producto, el grupo al que pertenece el producto, el producto como tal, el mercado en donde se tomó la medición y el precio promedio por kilogramo.

### Datos de insumos

La seres históricas de insumos tienen dos distintos sets de variables, ya que la tercer hoja del documento alberga el listado de los insumos, con 3 variables, el grupo del insumo, el subgrupo y el nombre del insumo/factor. Luego las demás hojas representan cada una un subgrupo ya establecido en la hoja del listado, estas cuentan con 8 variables, el año en que se tomó la medida, el mes, el codigo del departamento, el nombre del departamento, el codigo del municipio, el nombre del municipio, el nombre del producto, la presentación del producto y el precio promedio.

### Datos de abastecimiento
Las series históricas de abastecimiento tienen 38 variables, la fecha en la cual se tomó la medición, el total de abastecimiento, la variación mensual del abastecimiento, la variación anual del abastecimiento, dos variables de empalme, y de la número 7 a la 38 son distintos mercados en donde se tiene el valor de abastecimiento.

## Librerías usadas

A continuación un resumen de las librerías usadas y su propósito de uso

| Librería     | Propósito |
| ------------ | --------- |
| RColorBrewer | Generación de paletas de colores |
| readxl       | Lectura de archivos Excel |
| ggplot2      | Creación de gráficos estadísticos |
| tidyverse    | Conjunto de herramientas para el análisis de datos |
| cowplot      | Combinación de gráficos |
| lubridate    | Manejo de fechas y horas |
| patchwork    | Combinación de gráficos |
| tidyr        | Transformación de datos |
| dplyr        | Selección, manipulación y agregación de datos |
| lubridate    | Manejo de fechas y horas |
| skimr        | Exploración de datos |

## Explorando los datos
acá para abajo el código de análisis



